[package]
name = "lmx-core"
description = "The authoritative LMX provider engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
eventsource-stream.workspace = true
futures-util.workspace = true
image.workspace = true
percent-encoding.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tract-onnx = "0.22.0"

[dev-dependencies]
tokio.workspace = true
