/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ImageStream {
  constructor(requestJson: string)
  nextEventJson(): Promise<string | null>
  cancel(): void
}

export declare class ResponseSession {
  constructor(requestJson: string)
  executeRoundJson(): Promise<string>
  submitToolOutputsJson(outputsJson: string): string
  cancel(): void
  startRound(): void
  nextFrameJson(): Promise<string>
}

export declare function buildMessageItemJson(role: string, text: string): string

export declare function buildWireRequestJson(requestJson: string): string

export declare function generateImageJson(requestJson: string): Promise<string>

export declare function generateImagesJson(requestJson: string): Promise<string>

export declare function generateVideoJson(requestJson: string): Promise<string>

export declare function loadRequestContextJson(providerJson: string): string

export declare function normalizeToolOutputJson(callId: string, valueJson: string): string

export declare function outputTextFromItemsJson(itemsJson: string): string

export declare function providerRegistryJson(): string

export declare function toolFailureOutputJson(callId: string, error: string): string

export declare function version(): string
